export default {
  home: "/",
  signin: "/sign-in",
  signup: "/sign-up",
  account: "/account",
  watchList: "/watch-list",
  forgotPassword: "/forgot-password",
  activationLink: "/activate-account",
  products: "/products",
  product: "/product",
  categories: "/categories",
  category: "/category",
  help: "/help",
  deals: "/deals",
  shipto: "/ship-to",
  sell: "/sell",
  contact: "/contact",
  promo: "/promo/2024",
  api: {
    signup: "/api/user/signup",
    login: "/api/user/signin",
    activateAccount: "/api/user/account/activate",
    validateToken: "/api/user/verify/token",
  },
};
